name: Deploy Javadoc

on:  
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy JavaDoc specific version 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          project: maven
          target-folder: ${{ github.ref_name }}
  latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: javadoc
      - name: Create Root index
        run: echo "<script>window.location.replace('https://antaler.github.io/antaler/excel-creator/${{github.ref_name}}');</script>" > index.html
      - name: Commit Index
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[VERSION]"
          commit_message: "UPGRADE VERSION"
          force: false
          target_branch: master
            