name: Deploy Snapshot

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ossrh-snap
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.0

    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v5.0.0
      with:
        gpg_private_key: ${{ secrets.GPG_KEY }}
        passphrase: ${{ secrets.GPGP_PASSPHRASE }}

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}

    - name: Update Version
      run: mvn -B versions:set -DnewVersion=${{ steps.bump.outputs.version }}-SNAPSHOT -DgenerateBackupPoms=false

    - name: Publish to the Maven Central Repository
      run: mvn --batch-mode -s settings.xml -Dserver.id=ossrh-snap deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}